translate contributing.md to PT-BR
b2wads/grimorio-ui pull request #184
Opened 2020-10-04 14:25 UTC by LuizHAP

Fixes #175

Proposed Changes

Alteração do texto para português com adaptação do link mencionado no texto
  -
  -
  -

2020-10-05 14:07 UTC, apfzvd requested changes

2020-10-05 14:07 UTC, apfzvd commented on CONTRIBUTING.md
> +1. Fork esse repositório
Aqui acho melhor usar a expressão:
```suggestion
1. Faça um fork desse repositório.
```

Além disso, pode colocar ponto final em todos os itens? :D Apenas para manter um padrão!

2020-10-05 14:07 UTC, apfzvd commented on CONTRIBUTING.md
> +contribuintes e Mainteners nos comprometemos com a participação em nosso projeto e
Aqui (por mais feio que seja :P) acho melhor botar mantenedores ao invés de mantainers!
```suggestion
contribuintes e mantenedores nos comprometemos com a participação em nosso projeto e
```

2020-10-05 14:07 UTC, apfzvd commented on CONTRIBUTING.md
> +* Assumir responsabilidade, pedir desculpas às pessoas afetadas por nossos erros e aprender com a experiência
Vi que você adicionou esse item! Achei ótimo! Mas acabou omitindo um deles, sobre a linguagem inclusiva. Portanto sugiro:
```suggestion
* Usar uma linguagem inclusiva e receptiva
* Assumir responsabilidade, pedir desculpas às pessoas afetadas por nossos erros e aprender com a experiência
```

2020-10-05 14:07 UTC, apfzvd commented on CONTRIBUTING.md
> +A liderança do Projeto são responsáveis ​​por esclarecer os padrões de comportamento aceitável e devem tomar as ações corretivas adequadas e justas em resposta a quaisquer instâncias de comportamento
Com relação a alguns plurais, acho que ficaria melhor assim:

```suggestion
A liderança do Projeto é responsável ​​por esclarecer os padrões de comportamento aceitáveis e devem tomar as ações corretivas adequadas e justas em resposta a quaisquer instâncias de comportamento inaceitável.
```

2020-10-05 14:39 UTC, dehmirandac2 commented on CONTRIBUTING.md
> +nossa comunidade, que ela seja uma experiência livre de assédio para todos, independentemente da idade, corpo
Acho que tem uma vírgula depois de mantenedores. E eu sugeriria alterar um pouquinho uma parte. O que vocês acham?

```suggestion
Com o objetivo de promover um ambiente aberto e acolhedor, nós, como contribuintes e mantenedores, nos comprometemos a tornar a participação neste projeto e comunidade uma experiência livre de assédio para todos, independentemente da idade, corpo
```

2020-10-05 14:41 UTC, apfzvd commented on CONTRIBUTING.md
> +nossa comunidade, que ela seja uma experiência livre de assédio para todos, independentemente da idade, corpo
Perfeito @dehmirandac2!

2020-10-05 21:53 UTC, LuizHAP commented on CONTRIBUTING.md
> +contribuintes e Mainteners nos comprometemos com a participação em nosso projeto e
Eu acho horrivel essa palavra traduzida! Mas vou mandar bala!

2020-10-05 21:57 UTC, LuizHAP commented
Fiz as alterações novamente, poderiam revisar @apfzvd e @dehmirandac2?!
Me desculpe novamente pelos erros ortográficos, mas espero ter corrigido!

2020-10-05 22:01 UTC, apfzvd approved these changes

2020-10-05 22:03 UTC, apfzvd commented
> Fiz as alterações novamente, poderiam revisar @apfzvd e @dehmirandac2?!
> Me desculpe novamente pelos erros ortográficos, mas espero ter corrigido!

Por nada, isso acontece mesmo, haha. Ficou ótimo o documento! :star_struck: Por mim tá liberado! Vou pedir pra @dehmirandac2 dar uma olhada também :)

2020-10-06 00:39 UTC, dehmirandac2 commented
> Fiz as alterações novamente, poderiam revisar @apfzvd e @dehmirandac2?!
> Me desculpe novamente pelos erros ortográficos, mas espero ter corrigido!

Por mim fechou também! Valeu por contribuir com o nosso projeto, @LuizHAP 
:star2: :smiley:

2020-10-06 00:39 UTC, dehmirandac2 approved these changes

2020-10-06 13:40 UTC, merged